// Famous current NFL players by position
const players = [
  // Quarterbacks
  "Patrick Mahomes",
  "Josh Allen",
  "Lamar Jackson",
  "Joe Burrow",
  "Jalen Hurts",
  "Dak Prescott",
  "Justin Herbert",
  "Trevor Lawrence",
  "Brock Purdy",
  "Tua Tagovailoa",
  "C.J. Stroud",
  "Jordan Love",
  "Jared Goff",
  "Kirk Cousins",
  "Baker Mayfield",

  // Wide Receivers
  "Tyreek Hill",
  "Justin Jefferson",
  "CeeDee Lamb",
  "Ja'Marr Chase",
  "Stefon Diggs",
  "A.J. Brown",
  "Amon-Ra St. Brown",
  "Davante Adams",
  "Garrett Wilson",
  "DK Metcalf",
  "DeVonta Smith",
  "Chris Olave",
  "Puka Nacua",
  "Nico Collins",
  "Brandon Aiyuk",
  "Cooper Kupp",
  "Mike Evans",
  "Calvin Ridley",

  // Running Backs
  "Christian McCaffrey",
  "Derrick Henry",
  "Saquon Barkley",
  "Nick Chubb",
  "Josh Jacobs",
  "Jonathan Taylor",
  "Bijan Robinson",
  "Breece Hall",
  "De'Von Achane",
  "Kyren Williams",
  "Jahmyr Gibbs",
  "Rachaad White",
  "Kenneth Walker III",
  "Travis Etienne",
  "James Cook",
  "Alvin Kamara",
  "Joe Mixon",

  // Tight Ends
  "Travis Kelce",
  "Mark Andrews",
  "George Kittle",
  "T.J. Hockenson",
  "Sam LaPorta",
  "Evan Engram",
  "Dallas Goedert",
  "Kyle Pitts",
  "David Njoku",
  "Dalton Kincaid",
  "Jake Ferguson",
  "Trey McBride"
];

module.exports = players;
